// CaseCraft dataset
// Each case study follows the same schema so new entries can be appended in batches.
// Schema:
// slug, name, sector, oneLiner, founded, hq, founders, logoLetter,
// whatItDoes: [ {heading, body} ]
// moat: [ {heading, body} ]
// teardown: [ {heading, body} ]
// metrics: [ {label, value, note} ]
// improvements: [ {title, body} ]
// interview: [ {category, question, angle} ]

const SECTORS = [
  "Fintech & Payments",
  "Marketplaces & Travel",
  "SaaS & Productivity",
  "Streaming & Media",
  "Consumer & EdTech",
  "Quick Commerce & Retail",
  "Mobility & Logistics",
];

const CASE_STUDIES = [
  {
    slug: "stripe",
    name: "Stripe",
    sector: "Fintech & Payments",
    oneLiner: "Programmable infrastructure for moving and managing money online.",
    founded: "2010",
    hq: "South San Francisco, USA",
    founders: "Patrick Collison, John Collison",
    logoLetter: "S",
    whatItDoes: [
      { heading: "The core product", body: "Stripe is a developer-first payments and financial infrastructure company. At its core sits an API that lets any business accept a card or bank payment with roughly seven lines of code, but the company has since layered on a full financial operating system: Billing and Revenue Recognition for subscriptions, Radar for fraud detection, Connect for platforms that need to pay out sellers or drivers, Treasury and Issuing for embedded banking and card issuance, Tax for cross-border compliance, and, more recently, stablecoin settlement and wallet infrastructure through its acquisition of Privy and its own Tempo blockchain." },
      { heading: "Who uses it", body: "Stripe's customers range from single-person Shopify stores to roughly half of the Fortune 100. It processed about $1.9 trillion in total payment volume in 2025, equivalent to close to 1.6% of global GDP, across merchants in 50+ countries." },
      { heading: "How it makes money", body: "The primary revenue engine is a small percentage-plus-fixed-fee cut of every transaction (typically ~2.9% + 30 cents in the US), which nets out to roughly a 0.4% take rate after paying card networks and issuing banks. Adjacent product lines — Billing, Tax, Treasury — are usage-based add-ons layered on top of that core flow of funds." },
    ],
    moat: [
      { heading: "Developer mindshare and switching costs", body: "Stripe won the market by treating payments as a developer-experience problem rather than a sales problem: clean documentation, sandbox testing, and a single API surface for dozens of payment methods. Once a company's checkout, invoicing, subscription logic, tax calculation, and reconciliation all live inside Stripe's object model, ripping it out means rewriting core revenue infrastructure — a switching cost few engineering teams volunteer for." },
      { heading: "Platform economics via Connect", body: "Connect lets marketplaces (Instacart, DoorDash, Shopify) route payments to thousands of underlying sellers through Stripe. Every platform built on Connect brings its long tail of sub-merchants onto Stripe's rails without Stripe having to sell to them individually — a distribution moat that compounds as those platforms grow." },
      { heading: "Data and risk models", body: "Processing a meaningful share of global e-commerce volume gives Stripe's fraud engine, Radar, a training-data advantage that is very hard for a smaller processor to replicate, which in turn lets Stripe approve more legitimate transactions and reject more fraudulent ones — a flywheel that directly improves merchants' bottom line." },
      { heading: "Regulatory and banking-license depth", body: "Money movement requires money-transmitter licenses, banking partnerships, and compliance infrastructure in every jurisdiction served. Stripe has spent over a decade building this regulatory surface area, which is a multi-year, capital-intensive barrier for new entrants." },
    ],
    teardown: [
      { heading: "The wedge", body: "Stripe entered a market already served by PayPal and legacy processors, but targeted a specific pain: it took non-technical merchant-services salespeople weeks to get a business approved and integrated for card payments. Stripe let a developer go from signup to a working test charge in minutes, which won it the entire early-2010s cohort of startups building on the internet." },
      { heading: "Expansion pattern", body: "Stripe's strategy since has been to move up and down the money stack from that initial checkout wedge: down into infrastructure (Issuing, Treasury, its own card-present terminals), up into the business logic that sits on top of payments (Billing, Revenue Recognition, Tax), and sideways into new rails entirely (crypto and stablecoins via Tempo and Privy, aimed at cross-border and B2B settlement where card rails are expensive or slow)." },
      { heading: "Enterprise migration", body: "A large share of recent growth has come from migrating large enterprises off legacy processors like legacy bank-owned merchant acquirers, helped by regulatory tailwinds such as antitrust pressure on Apple's App Store commission, which could route billions in incremental iOS volume toward alternative processors including Stripe." },
      { heading: "Staying private", body: "Unlike most companies of its scale, Stripe has repeatedly chosen employee tender offers over an IPO, most recently valuing the company at $159B in a February 2026 secondary sale. This lets Stripe avoid quarterly guidance pressure while it invests in longer-payback bets like stablecoin rails." },
    ],
    metrics: [
      { label: "Total payment volume (2025)", value: "$1.9T", note: "+34% YoY" },
      { label: "Net revenue (2025, est.)", value: "~$6.9B", note: "Sacra estimate, +36% YoY" },
      { label: "Valuation (Feb 2026)", value: "$159B", note: "Employee tender offer" },
      { label: "Revenue & Finance Automation ARR", value: "~$1B run-rate (2026 target)", note: "Up from $500M in Feb 2025" },
      { label: "Stablecoin payment volume", value: "~$400B", note: "Doubled YoY; ~60% B2B" },
      { label: "Net take rate", value: "~0.4%", note: "After interchange & network costs" },
    ],
    improvements: [
      { title: "Close the SMB pricing-transparency gap", body: "Stripe's blended pricing is simple but can be materially more expensive than negotiated enterprise rates for high-volume SMBs. A tiered, self-serve volume-discount ladder (similar to cloud-provider pricing) could reduce churn to cheaper competitors like Square or regional processors without a sales-led renegotiation." },
      { title: "De-risk the stablecoin bet with clearer merchant use cases", body: "Tempo and Privy are infrastructure plays with unclear near-term merchant demand outside crypto-native and cross-border B2B niches. Publishing concrete, quantified case studies (e.g., settlement time and FX-cost savings vs. SWIFT) would help convert curiosity into adoption faster." },
      { title: "Deepen vertical-specific packaging", body: "Competitors like Adyen and vertical SaaS-embedded fintechs (Toast for restaurants, Mindbody for wellness) win by bundling payments with industry-specific workflow. Stripe could package pre-built compliance and workflow modules for its largest verticals (marketplaces, subscription software, healthcare) rather than leaving that work to platforms built on Connect." },
      { title: "Address IPO-readiness signaling", body: "Continued reliance on tender offers instead of a public listing creates liquidity uncertainty for long-tenured employees and could dampen recruiting versus newly-public peers like Figma. A clearer public roadmap (even a multi-year one) would reduce talent-retention risk." },
    ],
    interview: [
      { category: "Product sense", question: "Stripe wants to increase attach rate of Billing among merchants who only use core Payments. How would you design the experience?", angle: "A strong answer identifies the trigger moment (a merchant manually reconciling subscription revenue), proposes an in-product nudge tied to that moment rather than a generic upsell banner, and defines a success metric (e.g., % of new subscription businesses adopting Billing within 30 days) with a plan to avoid cannibalizing the simplicity that made Payments sticky." },
      { category: "Strategy", question: "Should Stripe go public? Argue both sides." },
      { category: "Metrics", question: "Stripe's net take rate is ~0.4%. What are the top 3 levers to grow revenue without raising headline pricing?", angle: "Look for: cross-sell of higher-margin adjacent products (Billing, Tax, Radar), volume growth via enterprise migration, and new rails (stablecoins) with structurally lower per-transaction cost that Stripe can price closer to card-rail levels while keeping more margin." },
      { category: "Guesstimate", question: "Estimate the annual revenue Stripe earns from a mid-size US e-commerce brand doing $50M/year in online sales." },
      { category: "Execution / RCA", question: "Chargeback rates spike 3x for a specific merchant category after a product launch. Walk through your root-cause and response process." },
    ],
  },

  {
    slug: "airbnb",
    name: "Airbnb",
    sector: "Marketplaces & Travel",
    oneLiner: "A two-sided marketplace connecting travelers with hosts renting out unique stays and experiences.",
    founded: "2008",
    hq: "San Francisco, USA",
    founders: "Brian Chesky, Joe Gebbia, Nathan Blecharczyk",
    logoLetter: "A",
    whatItDoes: [
      { heading: "The core product", body: "Airbnb is a marketplace app and website where hosts list spare rooms, entire homes, or unique properties, and guests search, book, and pay for stays. The platform handles discovery (search and recommendations), trust (reviews, identity verification, host guarantees), and transactions (payments, cancellation policies, messaging) between two strangers who've never met." },
      { heading: "Beyond stays", body: "Airbnb has extended into 'Experiences' (guided local activities hosted by locals) and, more recently, 'Services' (personal chefs, photographers, spa treatment bookable alongside a stay), an attempt to become the layer travelers open for anything beyond the flight and the hotel room itself." },
      { heading: "How it makes money", body: "Airbnb charges a service fee on both sides of the transaction — typically around 3% from hosts and a variable fee (usually 14–16%) from guests, bundled into the displayed price. Revenue is recognized at check-in rather than at booking, which is why 'Gross Booking Value' (GBV) is watched as the leading indicator of future revenue." },
    ],
    moat: [
      { heading: "Two-sided network effects", body: "More hosts in a city means more selection and lower prices for guests; more guest demand means better economics for hosts. This flywheel is strongest in Airbnb's long tail of non-hotel-market cities, where it has effectively created supply (spare bedrooms, vacation homes) that didn't previously exist as inventory for travelers." },
      { heading: "Trust infrastructure", body: "Reviews, identity verification, AirCover host/guest guarantees, and a decade of accumulated dispute-resolution data make it costly for a new entrant to replicate the baseline trust needed for strangers to transact. This is arguably a bigger moat than the listings themselves, since listings can be (and are) cross-posted to competitors." },
      { heading: "Brand as a generic verb", body: "'Airbnb' functions the way 'Google' does for search — a brand that has become synonymous with the category itself, which lowers customer-acquisition cost relative to challengers like Vrbo or Booking.com's rental arm." },
      { heading: "Host lock-in via tools, not contracts", body: "Airbnb doesn't require exclusivity, but pricing tools (Smart Pricing), calendar-sync, and the sheer volume of demand it channels make it the default primary channel for most hosts, even those who also list elsewhere." },
    ],
    teardown: [
      { heading: "The origin wedge", body: "Airbnb started by solving a hyper-specific problem: the founders rented airbeds in their apartment during a sold-out design conference. The initial product only worked because a acute, dated event created guaranteed demand and desperate hosts — a pattern (chasing conferences and events for cold-start liquidity) the company repeated deliberately in its first years." },
      { heading: "Solving the cold-start problem", body: "Early growth famously came from a scrappy tactic: the founders manually improved host listing photos and later built a (technically fragile) integration that cross-posted Airbnb listings to Craigslist, borrowing Craigslist's existing traffic to bootstrap demand before Airbnb had its own." },
      { heading: "From growth to trust crisis to trust-first product", body: "A widely publicized 2011 incident, where a host's apartment was ransacked by a guest, threatened to end the company. Airbnb's response — a $50,000 host guarantee, a dedicated trust and safety team, and 24/7 support — became a template: category-defining trust incidents are treated as product requirements, not PR problems." },
      { heading: "Post-IPO capital discipline", body: "Since going public in 2020, Airbnb has emphasized free cash flow and margin over aggressive geographic land-grab spending, a contrast to its 2010s growth-at-all-costs era, reflecting public-market pressure and a maturing core US/EMEA business." },
    ],
    metrics: [
      { label: "FY2025 revenue", value: "$12.24B", note: "+10% YoY" },
      { label: "FY2025 Gross Booking Value", value: "$91.27B", note: "+12% YoY" },
      { label: "Nights & experiences booked (2025)", value: "533M", note: "+8% YoY" },
      { label: "Q3 2025 Adjusted EBITDA margin", value: "~50%", note: "Highest quarterly margin on record" },
      { label: "TTM Free Cash Flow (Q3 2025)", value: "~$4.5B", note: "38% FCF margin" },
      { label: "Average nights per booking (2025)", value: "3.7", note: "Slightly down from 3.8 in 2024" },
    ],
    improvements: [
      { title: "Rebuild the 'unique stays' narrative", body: "As Airbnb inventory has professionalized (many hosts are now multi-property management companies), the original promise of 'live like a local' has eroded, and cleaning fees plus service fees have drawn public backlash for pricing opacity. Leaning harder into curated, distinctive inventory (via its 'Icons' and category pages) and simplifying total-price display would rebuild trust with price-sensitive travelers defecting to hotels." },
      { title: "Grow Experiences and Services into a real second revenue line", body: "Experiences has been relaunched multiple times without becoming material to revenue. A tighter integration — e.g., surfacing Experiences automatically inside a confirmed stay itinerary, rather than as a separate discovery surface — could improve attach rate." },
      { title: "Formalize a mid-to-long-stay product", body: "Post-pandemic remote work created durable demand for stays of a month or longer, a segment currently underserved relative to furnished-apartment platforms. A dedicated monthly-stay product with different trust, pricing, and cancellation mechanics could capture this without diluting the core weekend-trip experience." },
      { title: "Address regulatory fragmentation proactively", body: "City-by-city short-term-rental bans (New York's Local Law 18 being the starkest example) are a recurring tail risk. A standardized 'host compliance' toolkit that helps hosts navigate registration requirements city-by-city would reduce both host churn and headline regulatory risk." },
    ],
    interview: [
      { category: "Product sense", question: "Design a feature to help Airbnb guests trust a listing with zero reviews.", angle: "Look for: verified-identity signals, superhost-adjacent proxies (e.g., 'hosted by an experienced Superhost's portfolio'), limited-risk trial mechanics (flexible cancellation defaults for new listings), and a plan to measure whether the feature actually lifts new-listing conversion without just favoring existing power hosts." },
      { category: "Strategy", question: "Should Airbnb enforce exclusivity on hosts (i.e., penalize multi-platform listing)? Why or why not?" },
      { category: "Metrics", question: "GBV grew faster than revenue growth would suggest is 'normal' — what could explain the gap, and how would you verify each hypothesis?", angle: "Candidates should separate timing effects (revenue recognized at check-in vs. GBV recognized at booking) from real mix effects (ADR, nights per booking, geography mix) and propose which internal data cuts would confirm each." },
      { category: "Guesstimate", question: "Estimate the total addressable market for short-term home rentals in Japan." },
      { category: "Execution / RCA", question: "Bookings in a major city drop 20% week-over-week with no pricing change. Walk through your investigation." },
    ],
  },

  {
    slug: "notion",
    name: "Notion",
    sector: "SaaS & Productivity",
    oneLiner: "A flexible, block-based workspace for notes, docs, wikis, and databases — now expanding into AI agents.",
    founded: "2016 (relaunched)",
    hq: "San Francisco, USA",
    founders: "Ivan Zhao, Akshay Kothari",
    logoLetter: "N",
    whatItDoes: [
      { heading: "The core product", body: "Notion replaces a stack of separate tools — docs, wikis, task trackers, lightweight databases, and often spreadsheets — with a single canvas built from 'blocks' that can be rearranged, nested, and turned into structured databases. A page can start as a free-form note and evolve into a full project tracker without switching apps." },
      { heading: "Who uses it", body: "Notion's base spans individual note-takers and students on the free tier, through startup teams using it as an internal wiki, up to enterprise deployments that use it for cross-functional knowledge management, sitting alongside (and often replacing pieces of) Confluence, Asana, and Google Docs." },
      { heading: "The AI pivot", body: "Since 2024, Notion has layered AI features on top of its existing document graph: Notion AI for writing and Q&A, and more recently autonomous 'Agents' capable of multi-step tasks like updating databases or drafting documents from scattered source material — an attempt to make the AI feature the reason for upgrading to paid tiers, not just a novelty." },
      { heading: "How it makes money", body: "Notion sells seat-based subscriptions (Plus and Business plans, roughly $10–20/seat/month) with AI capabilities gated to higher tiers, plus enterprise contracts that add SSO, admin controls, and governance." },
    ],
    moat: [
      { heading: "Product-led growth virality", body: "Notion's growth has been driven almost entirely by users sharing public Notion pages (templates, personal wikis, team handbooks) which double as free marketing and onboarding for the next user. This kept customer-acquisition cost extremely low relative to sales-led competitors like Confluence or Asana." },
      { heading: "The flexible-block data model as a switching cost", body: "Because Notion doesn't force users into a single rigid structure (unlike a dedicated wiki or a dedicated task tool), teams end up encoding years of highly customized internal processes into their workspace. Migrating that idiosyncratic structure elsewhere is far harder than migrating a simple flat list of documents." },
      { heading: "Category ambiguity as strategic cover", body: "By refusing to be neatly categorized as 'just a wiki' or 'just a task tool,' Notion avoids head-to-head feature battles with focused incumbents in any single category, instead competing on being the single tool that replaces several." },
    ],
    teardown: [
      { heading: "The pivot that made Notion work", body: "Notion's first version (2016) was an ambitious no-code app builder that was technically impressive but too complex for most users and nearly ran the company out of money. The team rebuilt around a much simpler core abstraction — the block — and relaunched, trading ambition for usability, which unlocked the viral growth that followed." },
      { heading: "Retreat from 'the productivity bundle'", body: "Between 2021 and 2024, Notion pursued a strategy of directly replacing Microsoft Office and Google Workspace with standalone modules (Notion Mail, Notion Calendar, an acquired team-chat product via Campsite). By 2026 Notion had quietly wound most of this down — shutting Notion Mail and leaving Calendar without meaningful updates — in favor of a narrower bet: becoming the agent layer that operates across a company's existing SaaS tools rather than replacing all of them." },
      { heading: "Monetizing via AI without breaking the free flywheel", body: "Because Notion's growth depends on a generous free/individual tier, its main monetization lever has been packaging AI (a genuinely differentiated, costly-to-run feature) into paid tiers rather than raising prices on the core product — a way to expand ARPU without alienating the long tail of free users who drive viral distribution." },
      { heading: "Staying private and patient", body: "Notion reached a $10B valuation in 2021 and, unusually for a SaaS company of its visibility, didn't raise again until a 2026 tender offer — instead 'growing into' its valuation over several years of ARR growth (from roughly $100M in 2022 to $865M by mid-2026) rather than repricing every year." },
    ],
    metrics: [
      { label: "ARR (July 2026, est.)", value: "~$865M", note: "Sacra estimate, +82% YoY" },
      { label: "Valuation (Jan 2026 tender)", value: "$11B", note: "Up 10% from 2022's $10B" },
      { label: "Registered users", value: "100M+", note: "Company-reported" },
      { label: "Enterprise penetration", value: "50%+ of Fortune 500", note: "Company-reported" },
      { label: "Revenue multiple at 2026 tender", value: "~18x ARR", note: "Sacra estimate" },
    ],
    improvements: [
      { title: "Clarify the AI value proposition for non-technical teams", body: "Notion Agents' 'multi-step work' pitch resonates with technical, process-heavy teams but is abstract for the median small-team user who just wants better search or summarization. Shipping a small number of extremely concrete, named use cases (e.g., 'auto-update your roadmap from meeting notes') would convert curiosity into daily use faster than generalized agent messaging." },
      { title: "Rebuild trust after the productivity-bundle retreat", body: "Shutting down Notion Mail and leaving Calendar dormant signals strategy volatility to teams that adopted those tools in good faith. A clear, published statement of what Notion will and won't build going forward would reduce the risk of enterprise buyers hedging with a second tool." },
      { title: "Formalize a mid-market sales motion", body: "Notion's PLG motion is excellent at land, but enterprise-grade governance, security reviews, and procurement processes are where competitors with dedicated enterprise sales teams (Atlassian, Microsoft) win renewals. Investing in a proper mid-market/enterprise sales layer — without breaking the self-serve flywheel for smaller teams — is likely necessary before an IPO." },
      { title: "Reduce workspace performance degradation at scale", body: "A frequently cited user complaint is that very large Notion workspaces (thousands of pages, big databases) become slow. Solving this technical debt is table stakes for winning larger enterprise deployments where Confluence and SharePoint still have an edge at scale." },
    ],
    interview: [
      { category: "Product sense", question: "Design an onboarding flow for a new Notion Business customer's admin, optimized for team-wide adoption within the first month.", angle: "Strong answers focus on identifying a 'hero workspace' (e.g., migrating an existing wiki or tracker with a guided import), reducing the blank-page problem with role-specific templates, and defining an adoption metric (e.g., % of invited seats that create a page within 7 days) rather than just seat activation." },
      { category: "Strategy", question: "Notion shut down Notion Mail and largely abandoned Notion Calendar. Was retreating from the 'productivity bundle' strategy the right call?" },
      { category: "Metrics", question: "ARR grew 82% YoY but Notion's free-tier user base is enormous. What conversion and retention metrics would you want to see before concluding this growth is durable?", angle: "Look for: paid-seat conversion rate from free workspaces, net dollar retention within existing paid accounts, and AI-feature attach rate as a leading indicator, rather than just top-line ARR." },
      { category: "Guesstimate", question: "Estimate how many of Notion's 100M+ registered users are on a paid plan." },
      { category: "Execution / RCA", question: "A new AI Agents feature launches and support tickets about 'unexpected database changes' spike. How do you triage and respond?" },
    ],
  },

  {
    slug: "netflix",
    name: "Netflix",
    sector: "Streaming & Media",
    oneLiner: "The subscription streaming pioneer, now monetizing through price, advertising, and live sports.",
    founded: "1997",
    hq: "Los Gatos, USA",
    founders: "Reed Hastings, Marc Randolph",
    logoLetter: "N",
    whatItDoes: [
      { heading: "The core product", body: "Netflix streams a large licensed and original catalog of films, series, and increasingly live events (NFL games, boxing, WWE) on a subscription basis across nearly every internet-connected screen. The company's original content strategy, kicked off with House of Cards in 2013, was a deliberate hedge against the risk that studios would eventually pull licensed content to launch their own services — which they did." },
      { heading: "Tiering strategy", body: "Netflix now sells three tiers in most markets: an ad-supported plan (its fastest-growing), a standard ad-free plan, and a premium 4K/multi-device plan — a shift from its historical single-tier-per-price-point simplicity toward classic media-industry price discrimination." },
      { heading: "How it makes money", body: "Revenue is almost entirely subscription-based, with advertising becoming a meaningful secondary line: ad revenue is on track to roughly double year-over-year toward an approximate $3B target for 2026, driven by the ad-supported tier and live sports inventory, which commands premium ad rates." },
    ],
    moat: [
      { heading: "Content spend at a scale competitors can't easily match", body: "Netflix's global subscriber base (over 300 million paid memberships) lets it amortize a given piece of content across more paying users than any single-country competitor, which supports an annual content budget in the multi-billion-dollar range that smaller regional streamers cannot sustain." },
      { heading: "Recommendation and personalization data", body: "Nearly three decades of viewing data (dating back to DVD-by-mail ratings) feeds a recommendation system that keeps engagement high enough to justify price increases — Netflix's own research has long suggested personalization materially reduces churn." },
      { heading: "Local-content-as-global-content playbook", body: "Netflix's willingness to invest heavily in non-English originals (Squid Game, Money Heist, Wednesday) and then promote them globally has let it win audiences in markets where Western content alone wouldn't have been sufficient, a structural advantage over more US-centric competitors." },
      { heading: "First-mover trust with the living room", body: "Netflix's app is pre-installed or one-click-integrated on the vast majority of smart TVs, game consoles, and streaming sticks globally, a distribution advantage built over a decade that a new entrant would need years of hardware partnerships to replicate." },
    ],
    teardown: [
      { heading: "From DVD-by-mail to streaming (the original pivot)", body: "Netflix's founding business was a DVD rental-by-mail service, explicitly built to avoid Blockbuster's late fees. The company began investing in streaming infrastructure as early as 2007, cannibalizing its own profitable DVD business years before streaming was clearly the future — a textbook case of a company disrupting itself rather than waiting to be disrupted." },
      { heading: "The pivot to originals", body: "As content owners (Disney, WarnerMedia, NBCUniversal) began pulling licensed titles to launch their own direct-to-consumer services (Disney+, Max, Peacock), Netflix's multi-year head start in original production — an expensive, high-risk bet made years before the licensing threat fully materialized — became the reason it wasn't left with an empty catalog." },
      { heading: "The password-sharing crackdown", body: "Facing slowing subscriber growth in 2022, Netflix reversed a decade of tolerating shared passwords, rolling out paid-sharing enforcement globally. Rather than causing mass cancellations as some predicted, it converted a large share of freeloading households into new paying accounts, a rare example of monetizing away a beloved 'feature' without a subscriber backlash." },
      { heading: "The ad-tier and live-sports pivot", body: "After years of resisting advertising, Netflix launched an ad-supported tier in 2022 and has since pushed into live sports (NFL Christmas Day games, WWE Raw) specifically because live events sell at a premium CPM and can't be time-shifted or ad-skipped — directly targeting the TV advertising budgets that still dwarf pure streaming ad spend." },
    ],
    metrics: [
      { label: "Q2 2026 revenue", value: "$12.56B", note: "+13% YoY" },
      { label: "Q2 2026 net income", value: "$3.26B", note: "26.0% net margin" },
      { label: "Q2 2026 operating margin", value: "33.4%", note: "vs 34.1% in Q2 2025" },
      { label: "Paid memberships (Q1 2026)", value: "325M+", note: "Company stopped regular subscriber disclosure in 2025" },
      { label: "2026 ad revenue target", value: "~$3B", note: "Roughly doubling YoY" },
      { label: "Household penetration of addressable base", value: "<45%", note: "Per company commentary, implying continued room to grow" },
    ],
    improvements: [
      { title: "Make the ad tier's targeting parity explicit", body: "Advertisers still cite thinner targeting and measurement capability versus programmatic TV/YouTube as a reason for hesitancy. Faster progress on ad-tech maturity (beyond the Microsoft partnership) is likely the single biggest lever for hitting ambitious ad-revenue targets." },
      { title: "Manage price-hike fatigue", body: "Repeated price increases (two in just over a year in some markets) risk eroding goodwill, especially among ad-tier subscribers who already made a value-conscious choice. Netflix should consider slowing ad-free tier price increases while keeping the ad tier as the primary growth-and-margin lever." },
      { title: "Build a clearer live-sports identity", body: "Netflix's live-sports strategy so far is opportunistic (marquee one-off events) rather than a season-long rights portfolio like ESPN or Amazon's NFL deal. A more defined, recurring live-sports slate would create appointment viewing that materially reduces churn during content lulls." },
      { title: "Address gaming's lack of traction", body: "Netflix Games has not become a meaningful engagement or retention driver years after launch. Either a sharper strategic bet (e.g., tying games explicitly to flagship IP like Stranger Things) or scaling back investment would be more disciplined than continuing a diffuse, low-traction effort." },
    ],
    interview: [
      { category: "Product sense", question: "Design a feature to reduce churn specifically among ad-tier subscribers in their first 90 days.", angle: "Look for: identifying early churn signals (e.g., low first-week engagement), personalized onboarding around a subscriber's stated interests, and distinguishing price-sensitivity churn (which discounting can't fully solve) from content-fit churn (which recommendations can)." },
      { category: "Strategy", question: "Should Netflix bid aggressively for a full-season live sports rights package (e.g., an NBA or Premier League package), or stay opportunistic with marquee one-off events?" },
      { category: "Metrics", question: "Netflix stopped disclosing quarterly subscriber counts in 2025. What metrics would you propose disclosing instead, and what are the trade-offs?", angle: "Strong answers propose revenue-per-member or engagement-hours as more resistant-to-manipulation proxies, while acknowledging the trade-off of reduced competitive/analyst visibility into raw growth." },
      { category: "Guesstimate", question: "Estimate Netflix's total annual content spend as a percentage of revenue." },
      { category: "Execution / RCA", question: "A flagship new-season release underperforms viewership expectations by 40% in its first week despite strong marketing spend. How do you investigate?" },
    ],
  },

  {
    slug: "duolingo",
    name: "Duolingo",
    sector: "Consumer & EdTech",
    oneLiner: "A gamified, mobile-first language-learning app built on habit formation and free-to-play mechanics.",
    founded: "2011",
    hq: "Pittsburgh, USA",
    founders: "Luis von Ahn, Severin Hacker",
    logoLetter: "D",
    whatItDoes: [
      { heading: "The core product", body: "Duolingo teaches languages (and, more recently, math and music) through short, gamified lessons: streaks, XP points, leaderboards, hearts/lives, and a mascot (Duo the owl) whose notifications have become an internet meme in their own right. Courses are algorithmically adapted and increasingly built with AI assistance rather than purely human curriculum designers." },
      { heading: "Monetization tiers", body: "The app is free with ads and limited 'hearts' (mistakes allowed before a lesson locks), with a paid Super Duolingo subscription removing ads and hearts limits, and a further Max tier adding generative-AI features like conversational practice and personalized explanations." },
      { heading: "How it makes money", body: "Revenue comes primarily from subscriptions, supplemented by in-app advertising on the free tier and, to a smaller extent, the Duolingo English Test, a lower-cost alternative to TOEFL/IELTS accepted by a growing list of universities." },
    ],
    moat: [
      { heading: "Habit-formation as the actual product", body: "Duolingo's real competitive advantage isn't teaching efficacy in isolation — it's engagement design that gets users to open the app daily for years, which matters enormously for a category (language learning) where the historical failure mode is abandonment within weeks. Streaks, notifications, and social leaderboards are tuned obsessively via A/B testing at a scale most edtech competitors can't match." },
      { heading: "Data flywheel across a huge free user base", body: "A large free-tier user base generates enormous behavioral data on which lesson formats, notification timings, and difficulty curves drive retention — data that directly improves the product for the smaller paying cohort and can't be replicated by a competitor starting with a smaller user base." },
      { heading: "Brand recognition beyond the product", body: "Duo the owl's aggressive, meme-friendly notifications have made Duolingo one of the few edtech brands with organic, unpaid cultural relevance (viral social posts, brand crossovers), which lowers customer-acquisition cost versus competitors that must buy most of their attention." },
      { heading: "Course breadth funded by scale", body: "Offering 40+ languages, including very low-demand ones, is only viable because Duolingo's larger, popular courses (Spanish, French) subsidize the cost of building and maintaining the long tail — a scale advantage smaller language-learning apps can't match." },
    ],
    teardown: [
      { heading: "The original hook: free by design, not accident", body: "Duolingo was founded partly as a research project questioning whether translation exercises by language learners could crowdsource useful translation work (a model later dropped as machine translation improved). Free access wasn't just a growth tactic; it was existential to the founders' original mission of making language education free for people who couldn't afford Rosetta Stone-style paid software." },
      { heading: "Gamification as the wedge against 'boring' edtech", body: "Rather than compete on curriculum depth against traditional courses, Duolingo bet almost entirely on making the experience feel like a mobile game, correctly identifying that the biggest barrier to language learning for most people isn't access to content but consistency of practice." },
      { heading: "The efficacy-versus-engagement tension", body: "Duolingo has faced recurring criticism that its bite-sized exercises build vocabulary recognition better than real conversational fluency. The company's response — investing in AI-driven conversational practice (Max tier) and stealth-launching more rigorous 'Duolingo Math' and 'Duolingo Music' using the same engagement engine — is a bet that the retention mechanics, not the subject matter, are the transferable core asset." },
      { heading: "AI-first content production", body: "In 2023–2024 Duolingo controversially replaced a portion of its contract translator/content workforce with AI-assisted course generation, drawing public backlash but allowing much faster course expansion and update cycles — a preview of how the company intends to scale content without linearly scaling headcount." },
    ],
    metrics: [
      { label: "Q2 2026 DAUs", value: "58.7M", note: "+23% YoY" },
      { label: "Q2 2026 paid subscribers", value: "12.7M", note: "+17% YoY" },
      { label: "Q2 2026 revenue", value: "$298.5M", note: "+18% YoY" },
      { label: "Q2 2026 Adjusted EBITDA margin", value: "25.9%", note: "Down from 31.2% in Q2 2025" },
      { label: "Q1 2026 revenue", value: "$292.0M", note: "+27% YoY" },
      { label: "DAU-to-subscriber conversion", value: "~22%", note: "12.7M paid / 58.7M DAU, Q2 2026" },
    ],
    improvements: [
      { title: "Address the DAU-to-paid conversion gap", body: "DAUs are growing faster than paid subscribers (23% vs 17% YoY in Q2 2026), suggesting the free tier is winning attention faster than the paid tiers are winning wallets. More aggressive, well-timed paywalls around genuinely high-value features (rather than just hearts/ads removal) could close this gap without damaging the free habit loop that drives the top of funnel." },
      { title: "Prove out Max as more than a premium ad-remover", body: "The AI-powered Max tier's conversational-practice pitch needs clearer proof that it produces real fluency gains, not just novelty. Publishing independent efficacy research would help justify its premium price point and differentiate it from free AI chatbots users could otherwise use for practice." },
      { title: "Protect margin as AI compute costs scale", body: "Adjusted EBITDA margin compressed from 31.2% to 25.9% year-over-year in Q2 2026, plausibly reflecting rising AI inference costs for Max features. A clear plan to bring model costs down (smaller fine-tuned models, smarter caching) is important before Max becomes a larger share of the subscriber base." },
      { title: "Diversify beyond languages more deliberately", body: "Duolingo Math and Music are promising but still small relative to the core language business. A more deliberate cross-sell strategy — e.g., bundling a Math course recommendation for parents of language-learning kids — could accelerate their path to materiality." },
    ],
    interview: [
      { category: "Product sense", question: "DAU growth is outpacing paid-subscriber growth. Design a change to close that gap without hurting DAU retention.", angle: "Strong answers avoid the naive answer of 'just add more paywalls' and instead propose testing which specific friction points (ads, hearts limits, notification frequency) most correlate with eventual subscription, and target those surgically." },
      { category: "Strategy", question: "Should Duolingo expand aggressively into new subjects (math, music, chess) or double down on deepening the core language product?" },
      { category: "Metrics", question: "Adjusted EBITDA margin fell from 31.2% to 25.9% YoY even as revenue grew 18%. What would you check first to understand why?", angle: "Look for candidates separating cost-of-revenue drivers (AI inference for Max, App Store fees) from opex growth (marketing, headcount), and proposing which cohort-level data (e.g., margin per subscriber by tier) would isolate the cause." },
      { category: "Guesstimate", question: "Estimate how many hours per week the average Super Duolingo subscriber spends in the app." },
      { category: "Execution / RCA", question: "A new AI-generated course update causes a spike in 1-star reviews citing 'wrong answers marked correct.' Walk through your response plan in the first 48 hours." },
    ],
  },

  {
    slug: "zerodha",
    name: "Zerodha",
    sector: "Fintech & Payments",
    oneLiner: "India's largest discount stockbroker, built on zero-commission equity delivery and a bootstrapped, no-VC model.",
    founded: "2010",
    hq: "Bengaluru, India",
    founders: "Nithin Kamath, Nikhil Kamath",
    logoLetter: "Z",
    whatItDoes: [
      { heading: "The core product", body: "Zerodha lets Indian retail investors trade and invest in stocks, derivatives, mutual funds, and bonds through its flagship platform Kite, alongside Coin (direct mutual fund investing) and Console (portfolio reporting). It pioneered the 'discount broking' model in India: zero brokerage on equity delivery trades and a flat ₹20 (or 0.03%, whichever is lower) fee on intraday and derivatives trades, versus the percentage-of-trade-value commissions traditional full-service brokers charged." },
      { heading: "The broader ecosystem", body: "Beyond broking, the Kamath brothers built Zerodha Fund House (a low-cost mutual fund AMC), Zerodha Capital (loans against securities), Sensibull (options trading tools, acquired), and Rainmatter, a fund that invests in and incubates fintech and capital-markets startups adjacent to Zerodha's core business." },
      { heading: "How it makes money", body: "Revenue comes almost entirely from transaction-linked brokerage on futures & options (F&O) trading (flat fees per executed order) rather than equity delivery, which is genuinely free — meaning Zerodha's business model is unusually dependent on the volume and frequency of speculative derivatives trading among its user base." },
    ],
    moat: [
      { heading: "First-mover trust in a low-margin category", body: "Zerodha built its brand over 15 years as the discount broker that doesn't do the aggressive relationship-manager cold-calling and product-pushing that traditional brokers were known for, which built durable trust with self-directed retail investors even as cheaper new entrants (Groww) appeared." },
      { heading: "Bootstrapped capital efficiency", body: "Zerodha has never taken outside venture funding, which removed the growth-at-all-costs pressure that pushed VC-backed rivals to burn cash on aggressive customer acquisition. This let Zerodha remain one of India's most profitable brokerages by far, even while growing more slowly than subsidized competitors." },
      { heading: "Product depth (Kite, Coin, Console, Varsity)", body: "Zerodha built a genuinely deep product suite, including Varsity, one of the most widely used free financial-education resources in India, which built goodwill and trust among first-time investors years before they became active traders." },
      { heading: "Regulatory relationships and credibility", body: "As one of the longest-standing and most-scrutinized discount brokers, Zerodha has an unusually cooperative public posture with India's regulator (SEBI), including publicly supporting stricter F&O regulations that hurt its own short-term revenue — a credibility asset that's hard for newer, growth-focused competitors to match." },
    ],
    teardown: [
      { heading: "The founding insight", body: "Nithin Kamath had been a sub-broker for a full-service firm and saw firsthand how percentage-based brokerage commissions disincentivized brokers from actually caring whether clients made money — the broker got paid on volume regardless of client outcomes. Zerodha's flat-fee, zero-delivery-commission model was a direct structural fix to that misalignment." },
      { heading: "Riding, then being hit by, the F&O boom", body: "India's retail options-trading boom from 2020–2024 (accelerated by pandemic-era retail investing and easy account-opening via e-KYC) drove explosive growth for Zerodha and its VC-backed rivals alike. But when SEBI tightened F&O regulations in 2024–2025 (higher lot sizes, fewer weekly expiries) to protect retail traders from outsized derivatives losses, Zerodha's revenue fell for the first time in its 15-year history — a stark illustration of how concentrated its revenue is on the riskiest, most regulator-sensitive part of its business." },
      { heading: "Losing the client-count race, keeping the profit lead", body: "VC-funded Groww overtook Zerodha in active-client count by 2023 by spending heavily on acquisition, and the gap has widened since — Zerodha's market share of active NSE clients fell from roughly 22% in early 2023 to around 15% by mid-2026. Zerodha's public response has been to explicitly de-emphasize client-count as a vanity metric and point instead to assets under management (AUM), which continued growing even as active-client share declined." },
      { heading: "Rainmatter as a strategic hedge", body: "Rather than diversify Zerodha's own product line indefinitely, the founders built Rainmatter as a separate capital-allocation vehicle to fund the broader fintech ecosystem (climate-tech, capital-markets infrastructure, and adjacent fintechs) — spreading strategic bets without diluting focus on the core brokerage." },
    ],
    metrics: [
      { label: "FY25 revenue", value: "₹8,847 Cr (~$1.06B)", note: "-11.5% YoY, first-ever decline" },
      { label: "FY25 net profit", value: "₹4,200 Cr (~$505M)", note: "-23.6% YoY" },
      { label: "FY26 net profit", value: "₹4,238 Cr", note: "Roughly flat YoY" },
      { label: "Active NSE clients (July 2026)", value: "67.6 Lakh (6.76M)", note: "14.9% market share" },
      { label: "AUM (FY26)", value: "₹9.05 Lakh Cr (~$109B)", note: "Continues growing despite client-share decline" },
      { label: "Peak market share of active clients", value: "~22% (early 2023)", note: "Declined amid Groww's rise" },
    ],
    improvements: [
      { title: "Reduce dependence on F&O-linked revenue", body: "The FY25 revenue decline exposed how concentrated Zerodha's income is on speculative derivatives trading, which is both cyclical and a direct regulatory target. Accelerating monetization of AUM-linked products (its mutual fund AMC, Zerodha Capital's lending book, wealth advisory) would build a more resilient, less regulation-sensitive revenue base." },
      { title: "Decide deliberately on the growth-vs-profit trade-off", body: "Zerodha has explicitly chosen not to chase active-client count the way Groww has, but continued share erosion risks a long-term brand-relevance problem among first-time investors who now default to Groww. A targeted (not blanket) acquisition push aimed specifically at the segment most likely to become high-AUM long-term customers could defend share without abandoning capital discipline." },
      { title: "Expand internationally with the same low-cost playbook", body: "Zerodha's zero-commission, high-trust model hasn't been meaningfully exported outside India despite an addressable opportunity in other underpenetrated retail-investing markets in South/Southeast Asia, where similar full-service-broker inefficiencies exist." },
      { title: "Modernize the narrative around AMC fees", body: "Kamath has publicly noted AMC (account maintenance) fee increases are a small (~2%) share of revenue, but any fee increase on a brand built around 'zero cost' is reputationally risky. Clearer, proactive public communication about why such fees exist would preempt backlash better than reactive statements." },
    ],
    interview: [
      { category: "Product sense", question: "Design a feature that helps first-time Zerodha users avoid the common mistake of jumping straight into high-risk F&O trading.", angle: "Strong answers balance genuine investor protection with Zerodha's business reality (F&O drives most of its revenue), proposing friction (education gates, risk profiling) that's proportionate rather than punitive, and consider regulatory alignment with SEBI's own investor-protection push." },
      { category: "Strategy", question: "Zerodha has deliberately stayed bootstrapped and slower-growing than VC-backed Groww. Was this the right long-term strategy?" },
      { category: "Metrics", question: "Revenue fell 11.5% in FY25 while AUM kept growing. What does this divergence tell you about the health of the underlying business?", angle: "Look for candidates recognizing that AUM growth reflects durable long-term investor trust and asset stickiness, while the revenue decline reflects transaction-volume sensitivity to regulation — two very different signals that shouldn't be collapsed into one 'good/bad' verdict." },
      { category: "Guesstimate", question: "Estimate Zerodha's average revenue per active client per year." },
      { category: "Execution / RCA", question: "SEBI announces a new regulation next quarter that will further restrict weekly options expiries. Walk through how you'd model the revenue impact and what you'd do about it." },
    ],
  },

  {
    slug: "cred",
    name: "CRED",
    sector: "Fintech & Payments",
    oneLiner: "A members-only app that rewards on-time credit card bill payments, expanding into a broader personal-finance super app.",
    founded: "2018",
    hq: "Bengaluru, India",
    founders: "Kunal Shah",
    logoLetter: "C",
    whatItDoes: [
      { heading: "The core product", body: "CRED lets users pay their credit card bills through the app and earns them 'CRED Coins' redeemable for offers, brand deals, and members-only experiences. Access is gated by credit-worthiness criteria (a credit score threshold), an unusual design choice for a consumer app that deliberately excludes rather than maximizes total addressable users." },
      { heading: "Beyond bill payments", body: "CRED has expanded into CRED Money (an account-aggregator-based financial dashboard), CRED Cash (personal lines of credit), CRED Garage (vehicle and insurance management), a UPI payments product, and CRED Mint (peer-to-peer lending), positioning itself as a broader personal-finance layer for its affluent user base rather than a single-purpose bill-payment app." },
      { heading: "How it makes money", body: "Revenue comes from a mix of lending (interest and distribution fees on CRED Cash and managed AUM through partner NBFCs/banks), payment processing fees, advertising and brand-offer listing fees, and insurance/wealth distribution commissions — a genuinely diversified but still overall loss-making mix as of FY25." },
    ],
    moat: [
      { heading: "Curated exclusivity as a brand asset", body: "By restricting membership to users above a credit-score threshold, CRED built a brand perception of aspiration and exclusivity uncommon in Indian fintech, which let it charge premium advertising and offer-listing rates to brands wanting access to an affluent, creditworthy audience." },
      { heading: "High-value user base for lenders and brands", body: "CRED's members have both a demonstrated ability to service debt (they hold and pay off credit cards) and higher average transaction sizes than typical UPI apps — CRED's average UPI ticket size has been reported as several times higher than mass-market competitors — making the base valuable to lending partners and premium brands even without CRED having the largest raw user count." },
      { heading: "Data on repayment behavior", body: "Monitoring how members manage multiple credit cards gives CRED a real-time view into repayment behavior and financial stress signals that most lenders can't get elsewhere, an asset it monetizes by helping partner banks/NBFCs underwrite CRED Cash and other lending products." },
    ],
    teardown: [
      { heading: "The founding bet: reward good financial behavior", body: "Kunal Shah's thesis, built on his earlier experience founding FreeCharge, was that most fintech products in India rewarded transaction volume (cashback for spending) rather than good financial behavior (paying bills on time). CRED's original 'coins for on-time payment' hook was a genuinely novel wedge, even though it initially had a famously unclear path to revenue, sparking years of public skepticism about its business model." },
      { heading: "The 'debatable business model' years", body: "For its first several years, CRED was widely mocked in Indian tech media for extremely high customer-acquisition spend (including expensive, celebrity-heavy IPL sponsorship and viral ad campaigns) relative to a genuinely unclear monetization strategy — a valid criticism given the company posted revenue of just ₹52 lakh against large losses in FY20." },
      { heading: "The pivot to a lending-led super app", body: "From roughly 2022 onward, CRED shifted decisively toward being a lending and personal-finance platform (CRED Cash, CRED Money, wealth and insurance distribution) rather than purely a rewards/engagement app, finally giving the large, high-quality user base a monetization engine that matched its member profile." },
      { heading: "The leadership transition of 2026", body: "In a striking 2026 development, CRED raised $900M from Meta at a $4.5B valuation, and founder Kunal Shah stepped away from day-to-day leadership to lead WhatsApp globally, with Miten Sampat taking over as interim CEO — a major test of whether CRED's brand and strategy, built heavily around Shah's public persona, can persist under new leadership." },
    ],
    metrics: [
      { label: "FY25 operating revenue", value: "₹2,735 Cr (~$328M)", note: "+16% YoY" },
      { label: "FY25 operating loss", value: "₹298 Cr", note: "Down 51% YoY" },
      { label: "FY25 net loss (incl. non-operating)", value: "₹1,457–1,534 Cr", note: "Varies by filing; ESOP/depreciation-heavy" },
      { label: "Monthly transacting users (FY25)", value: "1.26 Cr (12.6M)", note: "+14.5% YoY" },
      { label: "Total payment value processed (FY25)", value: "₹8.5 Lakh Cr (~$102B)", note: "+23% YoY" },
      { label: "Valuation (post-Meta round, 2026)", value: "$4.5B", note: "Up from $3.64B in mid-2025 down round" },
    ],
    improvements: [
      { title: "Convert the Meta relationship into a real distribution advantage", body: "A $900M investment from Meta is an opportunity to explore deep WhatsApp integration (bill reminders, in-chat payments) that could meaningfully expand CRED's reach beyond its current premium-niche base, if structured without diluting the brand's exclusivity positioning." },
      { title: "Reach sustainable profitability without the founder's public brand", body: "CRED's marketing and brand identity have been unusually tied to Kunal Shah personally. With his departure to WhatsApp, CRED needs to establish an institutional brand identity independent of a single founder's public profile — a transition several Indian consumer-tech companies have struggled with." },
      { title: "Prove out lending quality through a credit cycle", body: "CRED's pivot to a lending-led model hasn't yet been tested through a serious credit downturn in India. Being transparent about portfolio quality (delinquency rates, underwriting standards) would build the credibility needed to keep partner banks/NBFCs comfortable expanding co-lending relationships." },
      { title: "Resolve the tension between exclusivity and scale", body: "The credit-score gating that built CRED's premium brand caps its total addressable market versus mass-market UPI competitors (PhonePe, Google Pay, and now WhatsApp Pay, which has already overtaken CRED on raw UPI volume). CRED should decide explicitly whether to defend a smaller, higher-value niche or cautiously loosen eligibility to grow volume, rather than drifting into that decision reactively." },
    ],
    interview: [
      { category: "Product sense", question: "Design a feature to increase CRED's average revenue per user among members who currently only use it for bill payments.", angle: "Strong answers propose a natural next product based on a member's existing signals (e.g., surfacing CRED Money for someone with multiple linked accounts, or CRED Cash for someone with irregular repayment timing) rather than a generic cross-sell banner, and define success as sustained usage, not just one-time activation." },
      { category: "Strategy", question: "Should CRED loosen its credit-score-based membership eligibility to grow scale, or keep its exclusivity-first positioning?" },
      { category: "Metrics", question: "CRED's operating loss narrowed 51% while revenue grew only 16%. What does that combination suggest, and what would you check to confirm it's sustainable?", angle: "Look for candidates distinguishing genuine operating leverage (fixed costs spread over more revenue) from one-time cost cuts (e.g., reduced marketing spend), and proposing which cohort or unit-economics data would separate the two." },
      { category: "Guesstimate", question: "Estimate CRED's average revenue per monthly transacting user." },
      { category: "Execution / RCA", question: "Three months after the Meta investment and leadership change, monthly transacting users decline for the first time in years. How would you investigate whether this is a brand/leadership-transition issue versus something else?" },
    ],
  },

  {
    slug: "zepto",
    name: "Zepto",
    sector: "Quick Commerce & Retail",
    oneLiner: "India's 10-minute grocery delivery platform, built on a dense dark-store network optimized for hyperlocal speed.",
    founded: "2021",
    hq: "Mumbai, India",
    founders: "Aadit Palicha, Kaivalya Vohra",
    logoLetter: "Z",
    whatItDoes: [
      { heading: "The core product", body: "Zepto delivers groceries and daily essentials — and increasingly electronics, beauty, and general merchandise — within roughly 10 minutes, using a dense network of small warehouses ('dark stores') placed within a couple of kilometers of dense residential clusters, rather than the 1–2 hour delivery windows of earlier grocery-delivery models like BigBasket." },
      { heading: "Zepto Cafe", body: "A dedicated quick-service coffee-and-snacks vertical launched in 2022, targeting a much higher order frequency (multiple times a week) than grocery baskets, and consequently a faster route to profitability per dark store." },
      { heading: "How it makes money", body: "Zepto earns through commissions on merchant-partner sales, advertising revenue from brands paying for placement (its fastest-growing and highest-margin line, up roughly 33x from FY24 to FY26), logistics/delivery charges, and direct procurement margins where it buys and resells inventory itself." },
    ],
    moat: [
      { heading: "Dark-store density as the actual moat", body: "10-minute delivery is only possible with a dark store within roughly 2km of most orders, which means the real competitive battle is over the best micro-locations in each city — a land-grab dynamic where the first mover to lock in a dense grid of well-placed small warehouses is very hard to dislodge without matching density, which itself requires huge capital." },
      { heading: "India-specific behavioral fit", body: "Hyperlocal, frequent small-basket shopping (rather than weekly bulk grocery runs) is a deeply established consumer habit in urban India, driven by small kitchen storage and a culture of buying fresh daily — a demand pattern quick commerce fits naturally, unlike in markets like the US where quick-commerce models (e.g., Getir, Gopuff) have struggled." },
      { heading: "Advertising as an emerging high-margin moat", body: "As order volumes have scaled (23.3 lakh average daily orders by Q4 FY26), Zepto's app has become valuable enough real estate that brands now pay meaningfully for placement — a moat that compounds as the platform's user base grows, similar to how Amazon's ad business scaled off its marketplace traffic." },
      { heading: "Founder-market fit and speed of execution", body: "Zepto's founders (Stanford dropouts in their early 20s) built and scaled the company at a speed (from founding to a multi-billion-dollar valuation in about 3 years) that let it catch up to and in some markets surpass earlier movers like Swiggy Instamart and BigBasket, reflecting an aggressive, capital-intensive execution culture." },
    ],
    teardown: [
      { heading: "The original wedge", body: "Founded in 2021 as 'KiranaKart' before rebranding to Zepto, the company bet that Indian consumers, especially in metros, would pay a premium for genuine 10-minute delivery over the 1–2 hour standard set by BigBasket and Grofers — a bet validated quickly enough that Blinkit (Zomato-owned) and Swiggy Instamart pivoted their own delivery-time promises to compete." },
      { heading: "The dark-store land grab", body: "Zepto's core strategy from 2022–2026 has been aggressive, capital-intensive expansion of its dark-store count (from 337 stores across 11 cities in FY24 to 1,139 stores across 66 cities by FY26), racing competitors to claim the best hyperlocal real estate before they could." },
      { heading: "From pure grocery to a broader retail platform", body: "Recognizing that grocery alone has thin margins, Zepto expanded into higher-margin categories (electronics, beauty, general merchandise) and stood up Zepto Cafe specifically to capture much higher order frequency, following the same 'start narrow, expand basket' playbook used by Swiggy and Zomato in food delivery." },
      { heading: "The IPO-readiness pivot", body: "As Zepto has moved toward a public listing (with a DRHP filed and under regulatory review as of early 2026), it has had to shift narrative from pure growth to a credible path to profitability, with the company noting many dark stores are now EBITDA-positive even as overall net losses remained large (₹3,367 Cr in FY25) — the classic quick-commerce tension between land-grab-stage losses and public-market demands for a profitability roadmap." },
    ],
    metrics: [
      { label: "Total dark stores (March 2026)", value: "1,139", note: "Across 66 cities, up from 337 in FY24" },
      { label: "FY26 total revenue (Net Receivables Value)", value: "₹24,815 Cr (~$3B)", note: "" },
      { label: "FY25 net loss", value: "₹3,367 Cr (~$405M)", note: "Widened from ₹1,215 Cr in FY24" },
      { label: "Average transacting users (March 2026)", value: "4.80 Cr (48M)", note: "Up from 1.06 Cr in FY24" },
      { label: "Ad revenue growth (FY24 to FY26)", value: "33x", note: "₹49.17 Cr to ₹1,635.73 Cr" },
      { label: "Expected IPO valuation (2026)", value: "$5.6–5.95B", note: "Reduced from an earlier $7B round" },
    ],
    improvements: [
      { title: "Narrow the path to group-level profitability before listing", body: "Individual dark-store EBITDA-positivity is encouraging but doesn't yet net out to company-level profit given corporate overhead, marketing, and expansion capex. A clearer, published multi-quarter profitability glidepath (not just per-store metrics) would strengthen IPO positioning relative to public-market scrutiny of loss-making consumer tech listings." },
      { title: "Diversify revenue away from pure commission and ad dependence on a still-thin-margin core", body: "With grocery commissions structurally thin, continued acceleration of the advertising business (already growing fast) and higher-margin categories (electronics, beauty) should be prioritized over further dark-store count growth in saturated metro markets." },
      { title: "Manage competitive intensity from well-capitalized rivals", body: "Blinkit (backed by Zomato/Eternal) and Swiggy Instamart are both public-company-backed and can absorb losses for longer. Zepto's differentiation needs to move beyond speed parity (which competitors have matched) toward assortment, pricing, or loyalty mechanics that are harder to copy quickly." },
      { title: "Address regulatory and antitrust scrutiny proactively", body: "Indian retail associations have sought antitrust probes into quick-commerce players' impact on traditional kirana stores. Proactively engaging with regulators and articulating a coexistence narrative (e.g., partnering with kirana stores as fulfillment nodes, as some competitors have done) could reduce headline regulatory risk ahead of an IPO." },
    ],
    interview: [
      { category: "Product sense", question: "Design a feature to increase order frequency among Zepto users who currently order only once a month.", angle: "Strong answers look for low-effort, high-frequency use cases (Zepto Cafe, small top-up items) rather than trying to convert an infrequent grocery shopper directly into a daily user, and propose a specific trigger (e.g., a post-delivery prompt for a frequently-forgotten small item) tied to a measurable frequency-lift metric." },
      { category: "Strategy", question: "Zepto is racing Blinkit and Swiggy Instamart on dark-store count. Is continued aggressive expansion the right priority right now, or should Zepto shift focus to profitability per store?" },
      { category: "Metrics", question: "Net losses widened to ₹3,367 Cr in FY25 even as the company says many individual dark stores are EBITDA-positive. How do you reconcile these two facts, and what would you want to see to judge overall business health?", angle: "Look for candidates separating store-level unit economics from corporate-level costs (marketing, tech, HQ overhead, new-store ramp losses), and proposing a cohort-based view (mature stores vs. newly opened stores) rather than a single blended loss number." },
      { category: "Guesstimate", question: "Estimate the average order value and implied gross margin per order for a Zepto grocery delivery in a metro city." },
      { category: "Execution / RCA", question: "A specific city's average delivery time creeps from 10 to 16 minutes over a month with no stated policy change. Walk through your root-cause investigation." },
    ],
  },

  {
    slug: "figma",
    name: "Figma",
    sector: "SaaS & Productivity",
    oneLiner: "Browser-based, real-time collaborative design software that redefined how product teams design together.",
    founded: "2012",
    hq: "San Francisco, USA",
    founders: "Dylan Field, Evan Wallace",
    logoLetter: "F",
    whatItDoes: [
      { heading: "The core product", body: "Figma is a vector design tool that runs entirely in the browser and lets multiple designers (and engineers, PMs, and stakeholders) edit the same file simultaneously in real time — the design equivalent of what Google Docs did to Microsoft Word. It replaced a workflow where designers worked in local files (Sketch, Photoshop) and exported static images for others to review." },
      { heading: "Beyond design files", body: "Figma has expanded into FigJam (a collaborative whiteboard for brainstorming and workshops), Dev Mode (a bridge that lets engineers inspect design specs and generated code directly), and, more recently, AI-assisted design generation features." },
      { heading: "How it makes money", body: "Figma sells seat-based subscriptions across a free tier, professional, organization, and enterprise plans, with pricing differentiated by collaboration limits, version history, and admin/security controls — a classic PLG-to-enterprise SaaS motion." },
    ],
    moat: [
      { heading: "Real-time multiplayer as a genuine technical moat", body: "Figma's core real-time collaborative-canvas engine (built on custom multiplayer infrastructure, not a bolted-on comments layer) was a multi-year technical undertaking that competitors struggled to replicate convincingly, which let Figma win the category even against Adobe's much larger resources and existing design-tool installed base." },
      { heading: "Network effects within design-adjacent teams", body: "Because a Figma file is genuinely useful to non-designers (PMs commenting, engineers inspecting specs in Dev Mode, marketers reviewing assets), adoption spreads within a company well beyond the design team that first purchased it, creating organic expansion that a single-player design tool never had." },
      { heading: "Browser-native distribution", body: "Requiring no install and working identically across Mac, Windows, and Chromebooks removed a major adoption barrier for design teams working across mixed operating systems or with contractors/freelancers who couldn't be trusted with an expensive desktop license." },
      { heading: "Community templates and plugins", body: "A large ecosystem of community-published templates, UI kits, and plugins (icon sets, accessibility checkers) increases switching costs the same way browser extensions and app-store ecosystems do for other platforms." },
    ],
    teardown: [
      { heading: "The multi-year technical bet", body: "Figma spent roughly four years in development before launching publicly in 2016, an unusually long, technically risky pre-launch period spent building browser-based real-time collaboration (a genuinely hard distributed-systems problem) rather than shipping a faster, less ambitious v1 — a bet that paid off once the product worked, but easily could have failed to ever ship." },
      { heading: "Land-and-expand via free individual use", body: "Figma's free tier for individuals and small teams let it spread organically among freelance and junior designers years before those users could influence a company-wide enterprise purchase — the same PLG playbook Notion and Slack used, adapted to a category where incumbents (Adobe, Sketch) had never offered a genuinely useful free product." },
      { heading: "The Adobe acquisition saga", body: "Adobe agreed to acquire Figma for $20B in 2022, at roughly 50x Figma's ARR — a deal that immediately tanked Adobe's own stock on investor skepticism about the price, and was ultimately abandoned in December 2023 after regulators in the UK and EU signaled they would block it on competition grounds, triggering a $1B breakup-fee payment to Figma." },
      { heading: "From acquisition target to independent public company", body: "Freed from the deal, Figma filed for and completed an IPO in July 2025, debuting at a $19B fully diluted valuation (briefly touching $47B market cap on its first trading day) on ARR that had grown from $400M (2022) to $749M (2024) — proof that its standalone growth trajectory alone justified public-market enthusiasm, without needing Adobe's distribution." },
    ],
    metrics: [
      { label: "ARR 2022 → 2024", value: "$400M → $749M", note: "~37% CAGR over the period" },
      { label: "IPO valuation (July 2025)", value: "$19B", note: "Fully diluted, at IPO pricing" },
      { label: "First-day market cap peak", value: "~$47B", note: "Before settling to a lower sustained valuation" },
      { label: "Q1 2025 revenue (pre-IPO filing)", value: "$228M", note: "With $44.9M net income" },
      { label: "Customers (as of March 2025)", value: "~450,000", note: "Company-disclosed in IPO filing" },
      { label: "Net dollar retention (2022, at Adobe deal time)", value: ">150%", note: "Company/Adobe disclosure at deal announcement" },
    ],
    improvements: [
      { title: "Defend against AI-native design tools", body: "A new generation of AI-first design/prototyping tools threatens to compress the 'idea to functioning prototype' workflow in ways that could bypass traditional vector-editing entirely. Figma's AI features need to move from incremental assistance (auto-layout suggestions) toward genuinely category-defining capability to avoid being outflanked the way it once outflanked Sketch." },
      { title: "Manage post-IPO growth-rate expectations", body: "Public-market investors will scrutinize whether Figma's ARR growth rate can sustain the multiple it IPO'd at as the market matures and enterprise penetration approaches saturation among large tech-forward companies. A credible new-market expansion story (e.g., deeper enterprise/regulated-industry penetration) is important for sustaining the growth narrative." },
      { title: "Solidify the Dev Mode wedge into engineering budgets", body: "Dev Mode is a genuine opportunity to expand Figma's budget line from 'design tooling' to a broader 'product development' spend category that includes engineering seats, but this requires proving concrete time savings for engineers, not just designers, to win budget conversations with engineering leadership." },
      { title: "Rebuild trust after the acquisition saga's uncertainty", body: "The nearly 15-month period of acquisition uncertainty (2022–2023) reportedly caused some employee attrition and customer hesitancy about Figma's independent future. Now as a public company, consistent execution against guidance is the clearest way to fully close that chapter with customers and talent." },
    ],
    interview: [
      { category: "Product sense", question: "Design a feature that helps engineering teams adopt Dev Mode more broadly within organizations that already use Figma for design.", angle: "Strong answers identify the actual friction (engineers not trusting generated code/specs, or not being looped in early enough) and propose a workflow change (e.g., automatic spec-diffing when a design changes after handoff) rather than just a marketing push, with a clear metric like % of engineering seats actively using Dev Mode." },
      { category: "Strategy", question: "How should Figma respond to the emergence of AI-native prototyping tools that let non-designers generate working interfaces from a text prompt?" },
      { category: "Metrics", question: "Figma's net dollar retention was reported above 150% in 2022. What does this metric capture, and what could cause it to decline as the company matures?", angle: "Look for a clear explanation that NDR captures expansion revenue from existing customers net of churn/downgrades, and reasoned hypotheses (market saturation among top customers, seat consolidation via AI-driven productivity, competitive losses) for why it might compress over time." },
      { category: "Guesstimate", question: "Estimate the total number of professional product designers globally, and what share of them are likely paying Figma customers." },
      { category: "Execution / RCA", question: "A major enterprise customer churns to a competitor shortly after a price increase. Walk through how you'd investigate whether this is a pricing, product, or service issue, and what you'd do about similarly at-risk accounts." },
    ],
  },

  {
    slug: "uber",
    name: "Uber",
    sector: "Mobility & Logistics",
    oneLiner: "A global multi-sided platform spanning ride-hailing, food and grocery delivery, and freight — now pursuing autonomous vehicles at scale.",
    founded: "2009",
    hq: "San Francisco, USA",
    founders: "Travis Kalanick, Garrett Camp",
    logoLetter: "U",
    whatItDoes: [
      { heading: "The core product", body: "Uber's app matches riders with nearby drivers for on-demand transportation (Mobility), matches diners with restaurants and delivery couriers (Delivery, via Uber Eats), and connects shippers with carriers for freight brokerage (Uber Freight) — three distinct marketplaces unified under one app, one driver/courier pool in many markets, and one loyalty program (Uber One)." },
      { heading: "The autonomous-vehicle pivot", body: "Rather than build its own self-driving technology after selling off its internal AV unit (Advanced Technologies Group) in 2020, Uber has repositioned itself as the demand-and-dispatch layer for third-party autonomous-vehicle operators (Waymo, and others), aiming to be 'the world's largest platform for autonomous vehicles' by integrating multiple AV fleets into its existing rider app rather than competing to build the cars itself." },
      { heading: "How it makes money", body: "Uber takes a percentage of Gross Bookings (the total dollar value of trips and orders) across all three segments, net of driver/courier earnings and, in some markets, direct payments to restaurants — with Mobility historically carrying the highest take rate and Delivery having improved substantially as the segment matured past its early loss-leading growth phase." },
    ],
    moat: [
      { heading: "Liquidity density in local markets", body: "Uber's core advantage in any given city is driver/courier density: more available drivers means shorter rider wait times, which attracts more riders, which in turn justifies more drivers staying online — a local network effect that is genuinely difficult for a new entrant to bootstrap against an incumbent with years of accumulated density." },
      { heading: "Cross-segment demand pooling", body: "Drivers and couriers can flex between Mobility and Delivery based on real-time demand (e.g., driving passengers during commute hours, delivering food during lunch and dinner peaks), which improves driver utilization and earnings consistency versus a single-purpose competitor — a structural advantage that pure-play rivals like Lyft or DoorDash don't have at the same scale." },
      { heading: "Data advantage for AV partnerships", body: "Over a decade of dispatch, routing, and demand-prediction data across hundreds of cities makes Uber a uniquely valuable demand-generation partner for AV operators like Waymo, who need reliable rider demand to make their expensive vehicle fleets utilization-efficient — turning Uber's marketplace data into leverage in AV partnership negotiations rather than needing to own the AV technology itself." },
      { heading: "Membership lock-in via Uber One", body: "A cross-segment subscription (discounted rides and free delivery) increases switching costs by tying loyalty to the combined platform rather than any single vertical, mirroring Amazon Prime's playbook of bundling otherwise-separate services into one subscription relationship." },
    ],
    teardown: [
      { heading: "The original wedge and early hyper-growth culture", body: "Uber launched as a premium black-car service before pivoting to the mass-market UberX product that actually drove its explosive growth, expanding into hundreds of cities simultaneously under aggressive, famously combative leadership (co-founder Travis Kalanick) that prioritized speed and regulatory confrontation over caution — a strategy that built massive scale quickly but also produced significant cultural and regulatory backlash." },
      { heading: "The 2017 leadership and culture reset", body: "A wave of public scandals in 2017 (workplace culture investigations, the #DeleteUber movement, executive departures) forced Kalanick's ouster and the appointment of Dara Khosrowshahi as CEO, who shifted Uber's strategy from confrontational growth-at-all-costs toward regulatory cooperation, safety investment, and a credible path to profitability ahead of its 2019 IPO." },
      { heading: "The pivot from 'build everything' to 'be the demand layer'", body: "Uber's early ambition included building its own autonomous-vehicle technology and its own food-delivery logistics from scratch, both extremely capital-intensive. Post-2020, the company shifted to a more capital-efficient posture: selling its AV unit rather than continuing to fund it alone, and generally preferring partnerships (with AV operators, with restaurants' own delivery fleets in some markets) over owning every layer of the stack." },
      { heading: "The path to durable profitability", body: "Uber posted its first full annual GAAP profit in 2023, years after founding and its 2019 IPO, driven by a combination of Delivery segment maturation (better restaurant/courier economics as density improved), Mobility recovery post-pandemic, and disciplined cost control — and has since compounded that into consistent double-digit gross-bookings growth alongside expanding operating margins and, as of 2026, trailing-twelve-month free cash flow exceeding $10B for the first time." },
    ],
    metrics: [
      { label: "Q2 2026 Gross Bookings", value: "$58.0B", note: "+24% YoY (+22% constant currency)" },
      { label: "Q2 2026 revenue", value: "$14.2B", note: "+12% YoY" },
      { label: "Q2 2026 trips", value: "3.9B", note: "+18% YoY" },
      { label: "Q2 2026 GAAP operating income", value: "$1.9B", note: "+30% YoY" },
      { label: "Monthly Active Platform Consumers (Q2 2026)", value: "208M", note: "+16% YoY" },
      { label: "TTM Free Cash Flow (2026)", value: ">$10B", note: "First time exceeding this threshold" },
    ],
    improvements: [
      { title: "Clarify the AV partnership economics long-term", body: "As Waymo and other AV operators scale, their bargaining leverage over Uber (which currently benefits from Uber's demand generation but doesn't have to share driver-marketplace economics with Uber long-term) could shift. Uber should pursue a more explicit, durable economic structure for AV partnerships now, rather than risk being disintermediated once AV fleets reach sufficient density to generate their own demand." },
      { title: "Address driver-earnings and regulatory pressure sustainably", body: "Ongoing regulatory pushes (in the EU, UK, and various US states) to reclassify gig drivers as employees, plus persistent driver advocacy around earnings transparency, represent a structural cost and legal risk. A proactive, generous-but-sustainable driver-benefits framework (rather than a reactive, market-by-market legal defense) would reduce both regulatory and reputational risk." },
      { title: "Improve delivery segment margins further", body: "Delivery Gross Bookings grew faster than Mobility in Q2 2026 (25% vs 20%), but Delivery still likely carries a lower take rate; continued investment in advertising revenue (similar to Amazon's and Zepto's playbooks) and grocery/retail delivery expansion could improve segment profitability further." },
      { title: "Reduce reliance on one-time investment gains for net income optics", body: "A meaningful share of Uber's recent net income growth has come from revaluation of equity stakes (e.g., in Aurora, and other AV/mobility investments) rather than core operations. Clearer separation of 'core operating profit' from 'investment gains' in external communication would build more durable investor trust in the underlying business quality." },
    ],
    interview: [
      { category: "Product sense", question: "Design a feature to improve driver utilization during off-peak hours when both Mobility and Delivery demand are low in a given city.", angle: "Strong answers propose leveraging Uber's cross-segment data to predict low-demand windows and test incentive or scheduling nudges (e.g., proactive surge-adjacent notifications, guaranteed minimum-earnings windows) rather than a generic blanket incentive, and define success via driver hours retained, not just short-term trip volume." },
      { category: "Strategy", question: "Should Uber invest in building its own autonomous-vehicle fleet, or continue as a pure demand-and-dispatch partner to third-party AV operators like Waymo?" },
      { category: "Metrics", question: "Uber's Q2 2026 net income grew faster than operating income due to a large equity-revaluation gain. How would you evaluate whether the underlying business quality is actually improving?", angle: "Look for candidates who isolate core metrics (operating margin, gross bookings growth, take rate trends) from one-time or non-operating items, and propose tracking operating income and free cash flow as the more durable signals of business health." },
      { category: "Guesstimate", question: "Estimate Uber's average take rate (revenue as a % of Gross Bookings) across its Mobility segment." },
      { category: "Execution / RCA", question: "A major city sees a 15% increase in rider cancellation rate over one month with no fare changes. Walk through your root-cause investigation and likely next steps." },
    ],
  },
];

if (typeof module !== "undefined") {
  module.exports = { SECTORS, CASE_STUDIES };
}
