import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {ArrowRight,ChevronLeft,Search,ExternalLink,Target,Layers,BarChart3,Compass,Lightbulb,ShieldCheck,Briefcase,Users,Menu,X} from "lucide-react";
import {cases} from "./cases";
import "./styles.css";

const names=Object.keys(cases);
const tabs=["Thesis","User & Problem","Product Teardown","Business","Metrics","Strategy","Opportunities","Risks","Sources"];

function App(){
 const [selected,setSelected]=useState(null),[tab,setTab]=useState("Thesis"),[q,setQ]=useState("");
 const filtered=names.filter(n=>n.toLowerCase().includes(q.toLowerCase()));
 if(selected) return <Case name={selected} tab={tab} setTab={setTab} back={()=>{setSelected(null);setTab("Thesis")}}/>;
 return <div><Header/><main className="home"><section className="hero"><div className="eyebrow">PRODCRAFT · DEEP PRODUCT RESEARCH</div><h1>How India's best<br/><i>products</i> actually work.</h1><p>Deep, opinionated product case studies built for people who want to understand the decisions behind India's most interesting products.</p><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a product..." /></div></section><section className="library"><div className="libraryHead"><div><div className="eyebrow">THE LIBRARY</div><h2>Flagship case studies</h2></div><span>{filtered.length} deeply researched</span></div><div className="cards">{filtered.map(n=><button className="caseCard" key={n} onClick={()=>setSelected(n)}><div className="cardTop"><span>{cases[n].sector}</span><b>{cases[n].score}</b></div><h3>{n}</h3><p>{cases[n].tagline}</p><small>Read case study <ArrowRight size={14}/></small></button>)}</div></section></main><footer>ProdCraft · Product intelligence for curious PMs</footer></div>
}
function Header({back}){return <header><div className="logo">Prod<span>Craft</span></div>{back?<button className="back" onClick={back}><ChevronLeft size={16}/> Library</button>:<div className="nav">Deep research · {names.length} flagship products</div>}</header>}
function Case({name,tab,setTab,back}){const c=cases[name];return <div><Header back={back}/><main className="case"><div className="caseHero"><div><div className="eyebrow">{c.sector}</div><h1>{name}</h1><p className="tagline">{c.tagline}</p></div><div className="score"><span>PRODUCT SCORE</span><b>{c.score}</b><small>/10</small></div></div><nav className="tabs">{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><div className="content">{tab==="Thesis"&&<Thesis c={c}/>} {tab==="User & Problem"&&<User c={c}/>} {tab==="Product Teardown"&&<Teardown c={c}/>} {tab==="Business"&&<Business c={c}/>} {tab==="Metrics"&&<Metrics c={c}/>} {tab==="Strategy"&&<Strategy c={c}/>} {tab==="Opportunities"&&<Opps c={c}/>} {tab==="Risks"&&<Risks c={c}/>} {tab==="Sources"&&<Sources c={c}/>}</div></main></div>}
const Section=({icon,title,children})=><section className="section"><div className="sectionTitle">{icon}<div><div className="eyebrow">CASE STUDY</div><h2>{title}</h2></div></div>{children}</section>;
function Thesis({c}){return <><Section icon={<Compass/>} title="The product thesis"><div className="thesis">{c.thesis}</div></Section><Section icon={<Target/>} title="Why this product is interesting"><div className="three"><div><b>THE USER PROMISE</b><p>{c.problem}</p></div><div><b>THE OPERATING ENGINE</b><p>{c.business}</p></div><div><b>THE PM QUESTION</b><p>What has to remain true for this product to keep winning as the market matures?</p></div></div></Section><Section icon={<BarChart3/>} title="At a glance"><div className="atglance"><div><span>SECTOR</span><b>{c.sector}</b></div><div><span>USER</span><b>{c.user}</b></div><div><span>CASE QUALITY</span><b>Research-led · fact / inference separated</b></div></div></Section></>}
function User({c}){return <><Section icon={<Users/>} title="Who is the user?"><div className="thesis">{c.user}</div><div className="two"><div className="panel"><b>Core problem</b><p>{c.problem}</p></div><div className="panel"><b>What users really hire it to do</b><p>Complete the high-value job with less uncertainty, friction and effort than the alternatives.</p></div></div></Section><Section icon={<Layers/>} title="The journey"><div className="journey">{c.journey.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></Section></>}
function Teardown({c}){return <Section icon={<Layers/>} title="Product teardown"><div className="teardown">{c.teardown.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></Section>}
function Business({c}){return <><Section icon={<Briefcase/>} title="How the business works"><div className="thesis">{c.business}</div><div className="flywheel">{c.flywheel.map((x,i)=><React.Fragment key={x}><div>{x}</div>{i<c.flywheel.length-1&&<ArrowRight size={15}/>}</React.Fragment>)}</div></Section><Section icon={<BarChart3/>} title="What creates the economic advantage"><div className="two"><div className="panel"><b>Scale effect</b><p>More successful usage should improve fixed-cost absorption, distribution efficiency or monetisation.</p></div><div className="panel"><b>Strategic constraint</b><p>The same mechanism that creates scale can become a risk if the company expands before local economics are proven.</p></div></div></Section></>}
function Metrics({c}){return <Section icon={<BarChart3/>} title="Product-specific metric tree"><div className="metrics">{c.metrics.map((x,i)=><article key={x[0]}><div className="metricNum">0{i+1}</div><div><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><div className="legend"><span>FACT</span> Publicly reported or directly supported · <span>PM VIEW</span> analytical recommendation</div></Section>}
function Strategy({c}){return <Section icon={<Compass/>} title="What should management optimise next?"><div className="strategy">{c.strategy.map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></Section>}
function Opps({c}){return <><Section icon={<Lightbulb/>} title="If I were the PM"><div className="opps">{c.opps.map((x,i)=><article key={x[0]}><div className="oppNum">0{i+1}</div><div><h3>{x[0]}</h3><p>{x[1]}</p><div className="tags"><span>{x[2]} IMPACT</span><span>{x[3]} EFFORT</span></div></div></article>)}</div></Section><Section icon={<Target/>} title="Prioritisation logic"><div className="thesis">Prioritise opportunities that strengthen the existing product advantage rather than adding features that create surface area without improving the core economic or user loop.</div></Section></>}
function Risks({c}){return <Section icon={<ShieldCheck/>} title="What could break the thesis?"><div className="risks">{c.risks.map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div></Section>}
function Sources({c}){return <Section icon={<ExternalLink/>} title="Research sources"><p className="sourceIntro">Sources are shown so the reader can distinguish reported facts from the product analysis layered on top.</p><div className="sources">{c.sources.map(s=><a href={s[1]} target="_blank" rel="noreferrer" key={s[1]}><div><b>{s[0]}</b><ExternalLink size={14}/></div><small>{s[1]}</small></a>)}</div></Section>}
createRoot(document.getElementById("root")).render(<App/>);
